<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Twilio\\' => array($vendorDir . '/twilio/sdk/Twilio'),
    'TrueBV\\' => array($vendorDir . '/true/punycode/src'),
    'Symfony\\Polyfill\\Php70\\' => array($vendorDir . '/symfony/polyfill-php70'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\Component\\HttpFoundation\\' => array($vendorDir . '/symfony/http-foundation'),
    'Symfony\\Component\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher'),
    'Stripe\\' => array($vendorDir . '/stripe/stripe-php/lib'),
    'Pusher\\' => array($vendorDir . '/pusher/pusher-php-server/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Omnipay\\TwoCheckoutPlus\\' => array($vendorDir . '/collizo4sky/omnipay-2checkout/src'),
    'Omnipay\\PayPal\\' => array($vendorDir . '/omnipay/paypal/src'),
    'Omnipay\\Mollie\\' => array($vendorDir . '/omnipay/mollie/src'),
    'Omnipay\\Braintree\\' => array($vendorDir . '/omnipay/braintree/src'),
    'Omnipay\\AuthorizeNet\\' => array($vendorDir . '/omnipay/authorizenet/src'),
    'Nabble\\' => array($vendorDir . '/nabble/semalt-blocker/src'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'Cocur\\Slugify\\' => array($vendorDir . '/cocur/slugify/src'),
    'Braintree\\' => array($vendorDir . '/braintree/braintree_php/lib/Braintree'),
);
